services:
  app:
    build: .
    container_name: impuestos-calculator
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.impuestos-http.rule=Host(`impuesto-calculator.dkuaik.dev`)"
      - "traefik.http.routers.impuestos-http.entrypoints=web"
      - "traefik.http.routers.impuestos-http.service=impuestos"
      - "traefik.http.routers.impuestos-https.rule=Host(`impuesto-calculator.dkuaik.dev`)"
      - "traefik.http.routers.impuestos-https.entrypoints=websecure"
      - "traefik.http.routers.impuestos-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.impuestos-https.service=impuestos"
      - "traefik.http.services.impuestos.loadbalancer.server.port=80"
    networks:
      - proxy

networks:
  proxy:
    external: true
