services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=enrq.rios.f@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik_letsencrypt:/letsencrypt"

  app:
    build: .
    container_name: impuestos-calculator
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.impuestos.rule=Host(`impuesto-calculator.dkuaik.dev`)"
      - "traefik.http.routers.impuestos.entrypoints=websecure"
      - "traefik.http.routers.impuestos.tls.certresolver=myresolver"
      - "traefik.http.services.impuestos.loadbalancer.server.port=80"

volumes:
  traefik_letsencrypt:
